### ISSUE TITLE
1.13+ Support

### ISSUE THREAD

**Issue by TheJimmyJ57** [HYPExMon5ter/UltimateEssentialsPro#16]
Support for 1.13.2 and 1.14.2

**Comment by HYPExMon5ter** [comment]
### Errors
- Admin Control
  - [20:38:44] [Server thread/ERROR]: Can't understand this loop: 'loop tree of {ue.aliases::*}' (3-UE_Admin_Control.sk, line 864: loop tree of {ue.aliases::*}:')
  - [20:38:44] [Server thread/ERROR]: Can't understand this loop: 'loop tree of {ue.aliases::*}' (3-UE_Admin_Control.sk, line 880: loop tree of {ue.aliases::*}:')
  - [20:38:44] [Server thread/ERROR]: Can't understand this loop: 'loop tree of {ue.aliases::*}' (3-UE_Admin_Control.sk, line 907: loop tree of {ue.aliases::*}:')
- Functions
  - [20:38:25] [Server thread/ERROR]: Can't understand this expression: 'placeholder from "%{_chat}%" for {_p}' (1-UE_Functions.sk, line 288: set {_papi} to placeholder from "%{_chat}%" for {_p}')
  - [20:38:27] [Server thread/ERROR]: Can't understand this loop: 'loop tree of {ue.settings.%{_page}%::*}' (1-UE_Functions.sk, line 631: loop tree of {ue.settings.%{_page}%::*}:')
- Core
  - [Server] ERROR can't understand this event: 'on tab complete' (2-UE_Core.sk, line 3641: on tab complete:')
- Extras
  - ERROR Can't understand this loop: 'loop tree of {ue.psettings.%{_page}%::*}' (5-UE_Extras.sk, line 322: loop tree of {ue.psettings.%{_page}%::*}:')

### Warnings
- Core
  - [20:38:40] [Server thread/WARN]: If you meant to make the variable {emojiList:::)} a list, its name should contain '::'. Having a single ':' does nothing! (2-UE_Core.sk, line 3800: set {emojiList:::)} to "?"')
  - [20:38:40] [Server thread/WARN]: If you meant to make the variable {emojiList:::(} a list, its name should contain '::'. Having a single ':' does nothing! (2-UE_Core.sk, line 3801: set {emojiList:::(} to "?"')
  - [20:38:40] [Server thread/WARN]: If you meant to make the variable {emojiList:::-)} a list, its name should contain '::'. Having a single ':' does nothing! (2-UE_Core.sk, line 3802: set {emojiList:::-)} to "?"')
- Admin Control
  - [20:38:44] [Server thread/WARN]: Possible name conflict of variables {motd.line.1} and {motd.line.%arg 2%} (there might be more conflicts). (3-UE_Admin_Control.sk, line 525: replace all "<totalplayers>" in {motd.line.1} with "%{_totalplayers}%"')
  - [20:38:44] [Server thread/WARN]: Possible name conflict of variables {motd.line.2} and {motd.line.%arg 2%} (there might be more conflicts). (3-UE_Admin_Control.sk, line 526: replace all "<totalplayers>" in {motd.line.2} with "%{_totalplayers}%"')
